/**
 * Comprehensive world currency list
 * { code, label, flag, symbol, country }
 */
export const WORLD_CURRENCIES = [
  // Africa
  { code: 'DZD', label: 'Algerian Dinar',          flag: '🇩🇿', symbol: 'DA',   country: 'Algeria' },
  { code: 'AOA', label: 'Angolan Kwanza',           flag: '🇦🇴', symbol: 'Kz',   country: 'Angola' },
  { code: 'XOF', label: 'West African CFA Franc',   flag: '🌍', symbol: 'CFA',  country: 'Benin / Burkina Faso / Côte d\'Ivoire / Guinea-Bissau / Mali / Niger / Senegal / Togo' },
  { code: 'BWP', label: 'Botswana Pula',            flag: '🇧🇼', symbol: 'P',    country: 'Botswana' },
  { code: 'BIF', label: 'Burundian Franc',          flag: '🇧🇮', symbol: 'Fr',   country: 'Burundi' },
  { code: 'CVE', label: 'Cape Verdean Escudo',      flag: '🇨🇻', symbol: '$',    country: 'Cape Verde' },
  { code: 'XAF', label: 'Central African CFA Franc',flag: '🌍', symbol: 'FCFA', country: 'Cameroon / CAR / Chad / Congo / Equatorial Guinea / Gabon' },
  { code: 'KMF', label: 'Comorian Franc',           flag: '🇰🇲', symbol: 'Fr',   country: 'Comoros' },
  { code: 'CDF', label: 'Congolese Franc',          flag: '🇨🇩', symbol: 'Fr',   country: 'Congo (DRC)' },
  { code: 'DJF', label: 'Djiboutian Franc',         flag: '🇩🇯', symbol: 'Fr',   country: 'Djibouti' },
  { code: 'EGP', label: 'Egyptian Pound',           flag: '🇪🇬', symbol: '£',    country: 'Egypt' },
  { code: 'ERN', label: 'Eritrean Nakfa',           flag: '🇪🇷', symbol: 'Nfk',  country: 'Eritrea' },
  { code: 'ETB', label: 'Ethiopian Birr',           flag: '🇪🇹', symbol: 'Br',   country: 'Ethiopia' },
  { code: 'GMD', label: 'Gambian Dalasi',           flag: '🇬🇲', symbol: 'D',    country: 'Gambia' },
  { code: 'GHS', label: 'Ghanaian Cedi',            flag: '🇬🇭', symbol: '₵',    country: 'Ghana' },
  { code: 'GNF', label: 'Guinean Franc',            flag: '🇬🇳', symbol: 'Fr',   country: 'Guinea' },
  { code: 'KES', label: 'Kenyan Shilling',          flag: '🇰🇪', symbol: 'KSh',  country: 'Kenya' },
  { code: 'LSL', label: 'Lesotho Loti',             flag: '🇱🇸', symbol: 'L',    country: 'Lesotho' },
  { code: 'LRD', label: 'Liberian Dollar',          flag: '🇱🇷', symbol: '$',    country: 'Liberia' },
  { code: 'LYD', label: 'Libyan Dinar',             flag: '🇱🇾', symbol: 'LD',   country: 'Libya' },
  { code: 'MGA', label: 'Malagasy Ariary',          flag: '🇲🇬', symbol: 'Ar',   country: 'Madagascar' },
  { code: 'MWK', label: 'Malawian Kwacha',          flag: '🇲🇼', symbol: 'MK',   country: 'Malawi' },
  { code: 'MRU', label: 'Mauritanian Ouguiya',      flag: '🇲🇷', symbol: 'UM',   country: 'Mauritania' },
  { code: 'MUR', label: 'Mauritian Rupee',          flag: '🇲🇺', symbol: '₨',    country: 'Mauritius' },
  { code: 'MAD', label: 'Moroccan Dirham',          flag: '🇲🇦', symbol: 'MAD',  country: 'Morocco' },
  { code: 'MZN', label: 'Mozambican Metical',       flag: '🇲🇿', symbol: 'MT',   country: 'Mozambique' },
  { code: 'NAD', label: 'Namibian Dollar',          flag: '🇳🇦', symbol: '$',    country: 'Namibia' },
  { code: 'NGN', label: 'Nigerian Naira',           flag: '🇳🇬', symbol: '₦',    country: 'Nigeria' },
  { code: 'RWF', label: 'Rwandan Franc',            flag: '🇷🇼', symbol: 'Fr',   country: 'Rwanda' },
  { code: 'STN', label: 'São Tomé Dobra',           flag: '🇸🇹', symbol: 'Db',   country: 'São Tomé and Príncipe' },
  { code: 'SCR', label: 'Seychellois Rupee',        flag: '🇸🇨', symbol: '₨',    country: 'Seychelles' },
  { code: 'SLL', label: 'Sierra Leonean Leone',     flag: '🇸🇱', symbol: 'Le',   country: 'Sierra Leone' },
  { code: 'SOS', label: 'Somali Shilling',          flag: '🇸🇴', symbol: 'Sh',   country: 'Somalia' },
  { code: 'ZAR', label: 'South African Rand',       flag: '🇿🇦', symbol: 'R',    country: 'South Africa' },
  { code: 'SSP', label: 'South Sudanese Pound',     flag: '🇸🇸', symbol: '£',    country: 'South Sudan' },
  { code: 'SDG', label: 'Sudanese Pound',           flag: '🇸🇩', symbol: '£',    country: 'Sudan' },
  { code: 'SZL', label: 'Swazi Lilangeni',          flag: '🇸🇿', symbol: 'L',    country: 'Eswatini' },
  { code: 'TZS', label: 'Tanzanian Shilling',       flag: '🇹🇿', symbol: 'Sh',   country: 'Tanzania' },
  { code: 'TND', label: 'Tunisian Dinar',           flag: '🇹🇳', symbol: 'DT',   country: 'Tunisia' },
  { code: 'UGX', label: 'Ugandan Shilling',         flag: '🇺🇬', symbol: 'Sh',   country: 'Uganda' },
  { code: 'ZMW', label: 'Zambian Kwacha',           flag: '🇿🇲', symbol: 'ZK',   country: 'Zambia' },
  { code: 'ZWL', label: 'Zimbabwean Dollar',        flag: '🇿🇼', symbol: '$',    country: 'Zimbabwe' },

  // Americas
  { code: 'USD', label: 'US Dollar',               flag: '🇺🇸', symbol: '$',    country: 'United States' },
  { code: 'CAD', label: 'Canadian Dollar',         flag: '🇨🇦', symbol: 'CA$',  country: 'Canada' },
  { code: 'MXN', label: 'Mexican Peso',            flag: '🇲🇽', symbol: '$',    country: 'Mexico' },
  { code: 'BRL', label: 'Brazilian Real',          flag: '🇧🇷', symbol: 'R$',   country: 'Brazil' },
  { code: 'ARS', label: 'Argentine Peso',          flag: '🇦🇷', symbol: '$',    country: 'Argentina' },
  { code: 'CLP', label: 'Chilean Peso',            flag: '🇨🇱', symbol: '$',    country: 'Chile' },
  { code: 'COP', label: 'Colombian Peso',          flag: '🇨🇴', symbol: '$',    country: 'Colombia' },
  { code: 'PEN', label: 'Peruvian Sol',            flag: '🇵🇪', symbol: 'S/',   country: 'Peru' },
  { code: 'UYU', label: 'Uruguayan Peso',          flag: '🇺🇾', symbol: '$',    country: 'Uruguay' },
  { code: 'PYG', label: 'Paraguayan Guaraní',      flag: '🇵🇾', symbol: '₲',    country: 'Paraguay' },
  { code: 'BOB', label: 'Bolivian Boliviano',      flag: '🇧🇴', symbol: 'Bs.',  country: 'Bolivia' },
  { code: 'VES', label: 'Venezuelan Bolívar',      flag: '🇻🇪', symbol: 'Bs.S', country: 'Venezuela' },
  { code: 'GYD', label: 'Guyanese Dollar',         flag: '🇬🇾', symbol: '$',    country: 'Guyana' },
  { code: 'SRD', label: 'Surinamese Dollar',       flag: '🇸🇷', symbol: '$',    country: 'Suriname' },
  { code: 'TTD', label: 'Trinidad & Tobago Dollar',flag: '🇹🇹', symbol: 'TT$',  country: 'Trinidad & Tobago' },
  { code: 'JMD', label: 'Jamaican Dollar',         flag: '🇯🇲', symbol: 'J$',   country: 'Jamaica' },
  { code: 'BBD', label: 'Barbadian Dollar',        flag: '🇧🇧', symbol: '$',    country: 'Barbados' },
  { code: 'BSD', label: 'Bahamian Dollar',         flag: '🇧🇸', symbol: '$',    country: 'Bahamas' },
  { code: 'BZD', label: 'Belize Dollar',           flag: '🇧🇿', symbol: '$',    country: 'Belize' },
  { code: 'DOP', label: 'Dominican Peso',          flag: '🇩🇴', symbol: 'RD$',  country: 'Dominican Republic' },
  { code: 'GTQ', label: 'Guatemalan Quetzal',      flag: '🇬🇹', symbol: 'Q',    country: 'Guatemala' },
  { code: 'HNL', label: 'Honduran Lempira',        flag: '🇭🇳', symbol: 'L',    country: 'Honduras' },
  { code: 'HTG', label: 'Haitian Gourde',          flag: '🇭🇹', symbol: 'G',    country: 'Haiti' },
  { code: 'NIO', label: 'Nicaraguan Córdoba',      flag: '🇳🇮', symbol: 'C$',   country: 'Nicaragua' },
  { code: 'CRC', label: 'Costa Rican Colón',       flag: '🇨🇷', symbol: '₡',    country: 'Costa Rica' },
  { code: 'PAB', label: 'Panamanian Balboa',       flag: '🇵🇦', symbol: 'B/.',  country: 'Panama' },
  { code: 'XCD', label: 'East Caribbean Dollar',   flag: '🌎', symbol: 'EC$',  country: 'Antigua / Dominica / Grenada / St Kitts / St Lucia / St Vincent' },
  { code: 'CUP', label: 'Cuban Peso',              flag: '🇨🇺', symbol: '$',    country: 'Cuba' },

  // Europe
  { code: 'EUR', label: 'Euro',                    flag: '🇪🇺', symbol: '€',    country: 'Eurozone' },
  { code: 'GBP', label: 'British Pound',           flag: '🇬🇧', symbol: '£',    country: 'United Kingdom' },
  { code: 'CHF', label: 'Swiss Franc',             flag: '🇨🇭', symbol: 'CHF',  country: 'Switzerland' },
  { code: 'NOK', label: 'Norwegian Krone',         flag: '🇳🇴', symbol: 'kr',   country: 'Norway' },
  { code: 'SEK', label: 'Swedish Krona',           flag: '🇸🇪', symbol: 'kr',   country: 'Sweden' },
  { code: 'DKK', label: 'Danish Krone',            flag: '🇩🇰', symbol: 'kr',   country: 'Denmark' },
  { code: 'PLN', label: 'Polish Złoty',            flag: '🇵🇱', symbol: 'zł',   country: 'Poland' },
  { code: 'CZK', label: 'Czech Koruna',            flag: '🇨🇿', symbol: 'Kč',   country: 'Czech Republic' },
  { code: 'HUF', label: 'Hungarian Forint',        flag: '🇭🇺', symbol: 'Ft',   country: 'Hungary' },
  { code: 'RON', label: 'Romanian Leu',            flag: '🇷🇴', symbol: 'lei',  country: 'Romania' },
  { code: 'BGN', label: 'Bulgarian Lev',           flag: '🇧🇬', symbol: 'лв',   country: 'Bulgaria' },
  { code: 'HRK', label: 'Croatian Kuna',           flag: '🇭🇷', symbol: 'kn',   country: 'Croatia' },
  { code: 'RSD', label: 'Serbian Dinar',           flag: '🇷🇸', symbol: 'din',  country: 'Serbia' },
  { code: 'ALL', label: 'Albanian Lek',            flag: '🇦🇱', symbol: 'L',    country: 'Albania' },
  { code: 'MKD', label: 'Macedonian Denar',        flag: '🇲🇰', symbol: 'ден',  country: 'North Macedonia' },
  { code: 'BAM', label: 'Bosnia-Herzegovina Mark', flag: '🇧🇦', symbol: 'KM',   country: 'Bosnia & Herzegovina' },
  { code: 'MDL', label: 'Moldovan Leu',            flag: '🇲🇩', symbol: 'L',    country: 'Moldova' },
  { code: 'UAH', label: 'Ukrainian Hryvnia',       flag: '🇺🇦', symbol: '₴',    country: 'Ukraine' },
  { code: 'RUB', label: 'Russian Ruble',           flag: '🇷🇺', symbol: '₽',    country: 'Russia' },
  { code: 'GEL', label: 'Georgian Lari',           flag: '🇬🇪', symbol: '₾',    country: 'Georgia' },
  { code: 'AMD', label: 'Armenian Dram',           flag: '🇦🇲', symbol: '֏',    country: 'Armenia' },
  { code: 'AZN', label: 'Azerbaijani Manat',       flag: '🇦🇿', symbol: '₼',    country: 'Azerbaijan' },
  { code: 'BYN', label: 'Belarusian Ruble',        flag: '🇧🇾', symbol: 'Br',   country: 'Belarus' },
  { code: 'ISK', label: 'Icelandic Króna',         flag: '🇮🇸', symbol: 'kr',   country: 'Iceland' },
  { code: 'TRY', label: 'Turkish Lira',            flag: '🇹🇷', symbol: '₺',    country: 'Turkey' },

  // Middle East
  { code: 'AED', label: 'UAE Dirham',              flag: '🇦🇪', symbol: 'AED',  country: 'United Arab Emirates' },
  { code: 'SAR', label: 'Saudi Riyal',             flag: '🇸🇦', symbol: 'SR',   country: 'Saudi Arabia' },
  { code: 'QAR', label: 'Qatari Riyal',            flag: '🇶🇦', symbol: 'QR',   country: 'Qatar' },
  { code: 'KWD', label: 'Kuwaiti Dinar',           flag: '🇰🇼', symbol: 'KD',   country: 'Kuwait' },
  { code: 'BHD', label: 'Bahraini Dinar',          flag: '🇧🇭', symbol: 'BD',   country: 'Bahrain' },
  { code: 'OMR', label: 'Omani Rial',              flag: '🇴🇲', symbol: 'OMR',  country: 'Oman' },
  { code: 'JOD', label: 'Jordanian Dinar',         flag: '🇯🇴', symbol: 'JD',   country: 'Jordan' },
  { code: 'ILS', label: 'Israeli New Shekel',      flag: '🇮🇱', symbol: '₪',    country: 'Israel' },
  { code: 'LBP', label: 'Lebanese Pound',          flag: '🇱🇧', symbol: 'LL',   country: 'Lebanon' },
  { code: 'IQD', label: 'Iraqi Dinar',             flag: '🇮🇶', symbol: 'IQD',  country: 'Iraq' },
  { code: 'IRR', label: 'Iranian Rial',            flag: '🇮🇷', symbol: '﷼',    country: 'Iran' },
  { code: 'YER', label: 'Yemeni Rial',             flag: '🇾🇪', symbol: '﷼',    country: 'Yemen' },

  // Asia
  { code: 'JPY', label: 'Japanese Yen',            flag: '🇯🇵', symbol: '¥',    country: 'Japan' },
  { code: 'CNY', label: 'Chinese Yuan',            flag: '🇨🇳', symbol: '¥',    country: 'China' },
  { code: 'INR', label: 'Indian Rupee',            flag: '🇮🇳', symbol: '₹',    country: 'India' },
  { code: 'KRW', label: 'South Korean Won',        flag: '🇰🇷', symbol: '₩',    country: 'South Korea' },
  { code: 'HKD', label: 'Hong Kong Dollar',        flag: '🇭🇰', symbol: 'HK$',  country: 'Hong Kong' },
  { code: 'SGD', label: 'Singapore Dollar',        flag: '🇸🇬', symbol: 'S$',   country: 'Singapore' },
  { code: 'TWD', label: 'Taiwan Dollar',           flag: '🇹🇼', symbol: 'NT$',  country: 'Taiwan' },
  { code: 'MYR', label: 'Malaysian Ringgit',       flag: '🇲🇾', symbol: 'RM',   country: 'Malaysia' },
  { code: 'THB', label: 'Thai Baht',               flag: '🇹🇭', symbol: '฿',    country: 'Thailand' },
  { code: 'IDR', label: 'Indonesian Rupiah',       flag: '🇮🇩', symbol: 'Rp',   country: 'Indonesia' },
  { code: 'PHP', label: 'Philippine Peso',         flag: '🇵🇭', symbol: '₱',    country: 'Philippines' },
  { code: 'VND', label: 'Vietnamese Dong',         flag: '🇻🇳', symbol: '₫',    country: 'Vietnam' },
  { code: 'BDT', label: 'Bangladeshi Taka',        flag: '🇧🇩', symbol: '৳',    country: 'Bangladesh' },
  { code: 'PKR', label: 'Pakistani Rupee',         flag: '🇵🇰', symbol: '₨',    country: 'Pakistan' },
  { code: 'LKR', label: 'Sri Lankan Rupee',        flag: '🇱🇰', symbol: '₨',    country: 'Sri Lanka' },
  { code: 'NPR', label: 'Nepalese Rupee',          flag: '🇳🇵', symbol: '₨',    country: 'Nepal' },
  { code: 'MMK', label: 'Myanmar Kyat',            flag: '🇲🇲', symbol: 'K',    country: 'Myanmar' },
  { code: 'KHR', label: 'Cambodian Riel',          flag: '🇰🇭', symbol: '៛',    country: 'Cambodia' },
  { code: 'LAK', label: 'Lao Kip',                 flag: '🇱🇦', symbol: '₭',    country: 'Laos' },
  { code: 'MNT', label: 'Mongolian Tögrög',        flag: '🇲🇳', symbol: '₮',    country: 'Mongolia' },
  { code: 'KZT', label: 'Kazakhstani Tenge',       flag: '🇰🇿', symbol: '₸',    country: 'Kazakhstan' },
  { code: 'UZS', label: 'Uzbekistani Som',         flag: '🇺🇿', symbol: 'so\'m',country: 'Uzbekistan' },
  { code: 'TJS', label: 'Tajikistani Somoni',      flag: '🇹🇯', symbol: 'SM',   country: 'Tajikistan' },
  { code: 'KGS', label: 'Kyrgyzstani Som',         flag: '🇰🇬', symbol: 'лв',   country: 'Kyrgyzstan' },
  { code: 'TMT', label: 'Turkmenistani Manat',     flag: '🇹🇲', symbol: 'T',    country: 'Turkmenistan' },
  { code: 'AFN', label: 'Afghan Afghani',          flag: '🇦🇫', symbol: '؋',    country: 'Afghanistan' },

  // Oceania
  { code: 'AUD', label: 'Australian Dollar',       flag: '🇦🇺', symbol: 'A$',   country: 'Australia' },
  { code: 'NZD', label: 'New Zealand Dollar',      flag: '🇳🇿', symbol: 'NZ$',  country: 'New Zealand' },
  { code: 'FJD', label: 'Fijian Dollar',           flag: '🇫🇯', symbol: '$',    country: 'Fiji' },
  { code: 'PGK', label: 'Papua New Guinean Kina',  flag: '🇵🇬', symbol: 'K',    country: 'Papua New Guinea' },
  { code: 'SBD', label: 'Solomon Islands Dollar',  flag: '🇸🇧', symbol: '$',    country: 'Solomon Islands' },
  { code: 'VUV', label: 'Vanuatu Vatu',            flag: '🇻🇺', symbol: 'Vt',   country: 'Vanuatu' },
  { code: 'WST', label: 'Samoan Tālā',             flag: '🇼🇸', symbol: 'T',    country: 'Samoa' },
  { code: 'TOP', label: 'Tongan Paʻanga',          flag: '🇹🇴', symbol: 'T$',   country: 'Tonga' },
];
